variable "admin_cidr" {}
variable "admin_dhcp" {}
variable "admin_dns" {}
variable "admin_gateway" {}
variable "admin_vlan" {}
variable "auth_token" {}
variable "barb_adminip" {}
variable "barb_intip" {}
variable "barb_pubip" {}
variable "billing_cycle" {}
variable "cinder_adminip" {}
variable "cinder_intip" {}
variable "cinder_pubip" {}
variable "compact" {}
variable "compute_admin_ips" {}
variable "compute_data_ips" {}
variable "compute_internal_ips" {}
variable "compute_names" {}
variable "compute_size" {}
variable "compute_storage_ips" {}
variable "controller_admin_ips" {}
variable "controller_data_ips" {}
variable "controller_internal_ips" {}
variable "controller_names" {}
variable "controller_public_ips" {}
variable "controller_size" {}
variable "controller_storage_ips" {}
variable "controller_storagerep_ips" {}
variable "dash_pubip" {}
variable "data_cidr" {}
variable "data_dhcp" {}
variable "data_gateway" {}
variable "data_vlan" {}
variable "db_admin_ips" {}
variable "db_internal_ips" {}
variable "db_names" {}
variable "db_size" {}
variable "dns_upstream" {}
variable "edge_hostname" {}
variable "edge_os" {}
variable "edge_size" {}
variable "external_vlan" {}
variable "glance_adminip" {}
variable "glance_intip" {}
variable "glance_pubip" {}
variable "heat_adminip" {}
variable "heat_intip" {}
variable "heat_pubip" {}
variable "internal_cidr" {}
variable "internal_dhcp" {}
variable "internal_gateway" {}
variable "internal_vlan" {}
variable "juju_admin_ips" {}
variable "juju_names" {}
variable "juju_size" {}
variable "jujuclient_ip" {}
variable "keystone_adminip" {}
variable "keystone_intip" {}
variable "keystone_pubip" {}
variable "local_vpn" {}
variable "magnum_pubip" {}
variable "magnum_intip" {}
variable "magnum_adminip" {}
variable "metro" {}
variable "mikrotik_link" {}
variable "mikrotik_version" {}
variable "ncc_adminip" {}
variable "ncc_intip" {}
variable "ncc_pubip" {}
variable "ntp_local" {}
variable "ntp_upstream" {}
variable "neutron_adminip" {}
variable "neutron_intip" {}
variable "neutron_pubip" {}
variable "os_external_subnet_size" {}
variable "os_external_subnet_tag" {}
variable "ossource" {}
variable "ovnc_admin_ips" {}
variable "ovnc_data_ips" {}
variable "ovnc_internal_ips" {}
variable "ovnc_names" {}
variable "ovnc_size" {}
variable "overlay_vlan" {}
variable "placement_adminip" {}
variable "placement_intip" {}
variable "placement_pubip" {}
variable "project_id" {}
variable "public_cidr" {}
variable "public_dhcp" {}
variable "public_gateway" {}
variable "public_vlan" {}
variable "pub_ip" {}
variable "rados_adminip" {}
variable "rados_intip" {}
variable "rados_pubip" {}
variable "remote_vpn" {}
variable "router_public_ips_net" {}
variable "router_public_ips_tag" {}
variable "safe_ip" {}
variable "storage_admin_ips" {}
variable "storage_cidr" {}
variable "storage_dhcp" {}
variable "storage_gateway" {}
variable "storage_internal_ips" {}
variable "storage_names" {}
variable "storage_storage_ips" {}
variable "storage_storagerep_ips" {}
variable "storage_size" {}
variable "storage_vlan" {}
variable "storagerep_cidr" {}
variable "storagerep_dhcp" {}
variable "storagerep_gateway" {}
variable "storagerep_vlan" {}
variable "ubuntu_user_pw" {}
variable "ubuntu_version" {}
variable "vault_adminip" {}
variable "vip_cidr" {}
